clusterName: junecao
controlPlane: 
    nodes: 
    - 195.17.180.59 
    - 195.17.82.202
    os: bottlerocket
    sshKey: /Users/junecao/.ssh/id_ed25519_eks
    sshUser: ec2-user
etcd: 
    nodes: 
    - 195.17.180.57 
    - 195.17.180.58 
    - 195.17.90.30 
    os: bottlerocket 
    sshKey: /Users/junecao/.ssh/id_ed25519_eks
    sshUser: ec2-user